---
- name: Зупинити контейнер Nginx
  hosts: all
  become: yes  # Запит підняття привілеїв sudo

  tasks:
    - name: Зупинити контейнер Nginx
      command: docker stop nginx_container_name  # Замініть nginx_container_name на ім'я вашого контейнера Nginx
      become: yes

