---
- name: Встановити та запустити Nginx на порту 8080
  hosts: all
  become: yes  # Запит підняття привілеїв sudo

  tasks:
    - name: Оновити пакетний кеш
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"  # Якщо ви користуєтеся Debian/Ubuntu

    - name: Встановити Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"  # Якщо ви користуєтеся Debian/Ubuntu

    - name: Запустити Nginx
      service:
        name: nginx
        state: started
      become: yes

    - name: Відкрити порт 8080 в файрволі
      ufw:
        rule: allow
        port: 8080
      become: yes
      when: ansible_service_mgr == "systemd"  # Якщо у вас systemd

    # Інші операції налаштування Nginx можна додати за необхідності

